server.port=8084
spring.application.name=expense-service

## Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/expenseiq_auth_db?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
### Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
### Eureka Configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.config.import=optional:configserver:http://localhost:8888

resilience4j.circuitbreaker.instances.expenseService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.expenseService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.expenseService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.expenseService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.expenseService.failureRateThreshold=50